# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/libunistring-feedstock/recipe, last modified Fri Aug 13 19:35:06 2021
# ------------------------------------------------

package:
  name: libunistring
  version: 0.9.10
source:
  fn: libunistring-0.9.10.tar.xz
  sha256: eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7
  url: http://ftpmirror.gnu.org/libunistring/libunistring-0.9.10.tar.xz
build:
  number: '0'
  run_exports:
    - libunistring >=0,<1.0a0
  string: h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host: []
  run: []
test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}
about:
  home: https://www.gnu.org/software/libunistring
  license: LGPL
  summary: This library provides functions for manipulating Unicode strings and for
    manipulating C strings according to the Unicode standard.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bgruening
    - chenghlee
    - stefan-balke
