# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/nettle-feedstock/recipe, last modified Fri Aug 13 20:11:13 2021
# ------------------------------------------------

package:
  name: nettle
  version: 3.7.3
source:
  fn: nettle-3.7.3.tar.gz
  sha256: 661f5eb03f048a3b924c3a8ad2515d4068e40f67e774e8a26827658007e3bcf0
  url: https://ftp.gnu.org/gnu/nettle/nettle-3.7.3.tar.gz
build:
  number: '1'
  run_exports:
    - nettle >=3.7.3,<3.8.0a0
  string: h84b5d62_1
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - perl 5.34.0 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - gmp 6.2.1 hc377ac9_0
    - libcxx 12.0.0 hf6beb65_1
  run:
    - gmp >=6.2.1,<7.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libnettle.a
    - test ! -f ${PREFIX}/lib/libhogweed.a
about:
  description: Nettle is a low-level cryptographic library that is designed to fit
    easily in more or less any context. In crypto toolkits for object-oriented languages
    (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel
    space. Simple, fast, extensible JSON encoder/decoder for Python
  dev_url: https://git.lysator.liu.se/nettle/nettle
  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_family: GPL
  license_file: /Users/ktietz/demo/src/aggregate/nettle-feedstock/recipe/LICENSE
  summary: Nettle is a low-level cryptographic library that is designed to fit easily
    in more or less any context
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - sachalau
