# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/libidn2-feedstock/recipe, last modified Sat Aug  7 09:29:23 2021
# ------------------------------------------------

package:
  name: libidn2
  version: 2.3.1
source:
  sha256: 8af684943836b8b53965d5f5b6714ef13c26c91eaa36ce7d242e3d21f5d40f2d
  url: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.1.tar.gz
build:
  number: '0'
  run_exports:
    - libidn2 >=2,<3.0a0
  string: h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - libunistring 0.9.10 h1a28f6b_0
  run:
    - libunistring >=0,<1.0a0
test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libidn2.a"
about:
  home: https://www.gnu.org/software/libidn/#libidn2
  license: LGPLv2 AND LGPL-3.0-or-later AND GPL-3.0-or-later
  license_file: COPYING
  summary: Library for internationalized domain names (IDNA2008) support
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - hmaarrfk
