# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_82_4en_via/clone/recipe, last modified Fri Mar  3 05:08:15 2023
# ------------------------------------------------

package:
  name: libpng
  version: 1.6.39
source:
  patches:
    - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    - 0002-Ensure-that-lm-is-not-included-in-Windows-pkg-config.patch
  sha256: af4fb7f260f839919e5958e5ab01a275d4fe436d45442a36ee62f73e5beb75ba
  url: https://download.sourceforge.net/libpng/libpng-1.6.39.tar.gz
build:
  number: '0'
  run_exports:
    - libpng >=1.6.39,<1.7.0a0
  string: h80987f9_0
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - automake 1.16.5 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 h7ec7a93_1
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1a28f6b_2
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - zlib 1.2.13 h5a0b063_0
  run:
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
    - libpng-config --version
about:
  description: 'libpng is the official PNG reference library. It supports almost all
    PNG

    features, is extensible, and has been extensively tested for over 20 years.

    '
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  doc_url: http://www.libpng.org/pub/png/libpng.html
  home: http://www.libpng.org/pub/png/libpng.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: PNG reference library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 828e78fd-9d41-4db7-b26f-973b5c23c6ba
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/libpng-feedstock.git
  sha: cb4734baa7676085ec79b6d3a95cba5460ef27a7
