# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_771olrhiqw/clone/recipe, last modified Tue Oct 18 15:39:33 2022
# ------------------------------------------------

package:
  name: idna
  version: '3.4'
source:
  sha256: 814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4
  url: https://pypi.io/packages/source/i/idna/idna-3.4.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_771olrhiqw/croot/idna_1666125579282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vvv
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.07.19 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hc377ac9_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1q h1a28f6b_0
    - pip 22.2.2 py39hca03da5_0
    - python 3.9.13 hbdb9e5c_2
    - readline 8.1.2 h1a28f6b_1
    - setuptools 63.4.1 py39hca03da5_0
    - sqlite 3.39.3 h1058600_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022e h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.12 h5a0b063_3
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - idna
    - idna.codec
    - idna.compat
  requires:
    - pip
about:
  description: 'A library to support the Internationalised Domain Names in Applications

    (IDNA) protocol as specified in RFC 5891. This version of the protocol

    is often referred to as "IDNA2008".

    '
  dev_url: https://github.com/kjd/idna
  doc_url: https://github.com/kjd/idna/blob/master/README.rst
  home: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 776ecfe5-d875-4dbc-adb9-538c8bcd40a6
  recipe-maintainers:
    - goanpeca
    - jschueller
  remote_url: git@github.com:AnacondaRecipes/idna-feedstock.git
  sha: e08109603646ed4a27e09a78107f0c8166543787
