# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/libopus-feedstock/recipe, last modified Sat Aug 14 09:09:45 2021
# ------------------------------------------------

package:
  name: libopus
  version: '1.3'
source:
  sha256: 65b58e1e25b2a114157014736a3d9dfeaad8d41be1c8179866f144a2fb44ff9d
  url: https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
build:
  number: '1'
  run_exports:
    - libopus >=1.3,<2.0a0
  string: h1a28f6b_1
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - automake 1.16.2 pl5340hca03da5_0
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.4.13 hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - curl 7.71.1 h6b60437_1
    - expat 2.4.1 hc377ac9_2
    - gettext 0.21.0 h826f4ad_0
    - git 2.32.0 pl5340h646bd76_1
    - icu 68.1 hc4ed4cf_0
    - krb5 1.19.1 h8e9bd5e_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210216 h1230e6a_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libssh2 1.9.0 h7405173_1
    - libtool 2.4.6 h1230e6a_0
    - libxml2 2.9.10 h3d7e406_3
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pcre2 10.37 h4e217f5_0
    - perl 5.34.0 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - tk 8.6.10 h6b60437_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run: []
test:
  commands:
    - test -f ${PREFIX}/lib/libopus.a
    - test -f ${PREFIX}/lib/libopus.dylib
    - conda inspect linkages -p $PREFIX libopus
    - conda inspect objects -p $PREFIX libopus
about:
  description: 'Opus is a totally open, royalty-free, highly versatile

    audio codec. Opus is unmatched for interactive speech

    and music transmission over the Internet, but is also

    intended for storage and streaming applications. It is

    standardized by the Internet Engineering Task Force

    (IETF) as RFC 6716 which incorporated technology from

    Skype''s SILK codec and Xiph.Org''s CELT codec.

    '
  dev_url: http://opus-codec.org/development/
  doc_url: http://opus-codec.org/docs/
  home: http://opus-codec.org/
  license: 3-clause BSD
  license_family: BSD
  summary: Opus Interactive Audio Codec
extra:
  copy_test_source_files: true
  final: true
