# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_28kpg0z8cu/clone/recipe, last modified Mon Feb 27 02:29:00 2023
# ------------------------------------------------

package:
  name: libdeflate
  version: '1.17'
source:
  sha256: fa4615af671513fa2a53dc2e7a89ff502792e2bdfc046869ef35160fcc373763
  url: https://github.com/ebiggers/libdeflate/archive/v1.17.tar.gz
build:
  number: '0'
  run_exports:
    - libdeflate >=1.17,<1.18.0a0
  string: h80987f9_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.4.9 hc377ac9_0
    - krb5 1.19.4 h8380606_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcurl 7.87.0 h0f1d93c_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - lz4-c 1.9.4 h313beb8_0
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - rhash 1.4.1 hf27765b_1
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.2 h8574219_0
  run: []
test:
  commands:
    - test ! -f ${PREFIX}/lib/libdeflate.a
    - test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}
    - test -f ${PREFIX}/include/libdeflate.h
    - libdeflate-gzip -h
    - libdeflate-gunzip -h
about:
  description: 'libdeflate is heavily optimized. It is significantly faster than the
    zlib

    library, both for compression and decompression, and especially on x86

    processors. In addition, libdeflate provides optional high compression

    modes that provide a better compression ratio than the zlib''s "level 9".

    '
  dev_url: https://github.com/ebiggers/libdeflate
  doc_url: https://github.com/ebiggers/libdeflate/blob/master/README.md
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression
    and decompression.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 28d92bc5-8844-43b5-a4c5-3704670f0bad
  recipe-maintainers:
    - dpryan79
    - hmaarrfk
    - rhpvorderman
  remote_url: git@github.com:AnacondaRecipes/libdeflate-feedstock.git
  sha: 7b85bce83f9869d1278ecc239613813c9e4aa0ae
