# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_47c5juxes5/clone/recipe, last modified Thu Jan 26 05:53:24 2023
# ------------------------------------------------

package:
  name: ncurses
  version: '6.4'
source:
  fn: ncurses-6.4.tar.gz
  patches:
    - clang.patch
    - fix.patch
  sha256: 6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
  url: https://invisible-mirror.net/archives/ncurses/ncurses-6.4.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - libstdcxx-ng
  number: '0'
  run_exports:
    - ncurses >=6.4,<7.0a0
  string: h313beb8_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 h7ec7a93_1
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - libcxx 14.0.6 h848a8c0_0
    - libiconv 1.16 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
  run: []
test:
  requires:
    - pkg-config
about:
  description: 'The ncurses (new curses) library is a free software

    emulation of curses in System V Release 4.0 (SVr4),

    and more. It uses terminfo format, supports pads and

    color and multiple highlights and forms characters and

    function-key mapping, and has all the other SVr4-curses

    enhancements over BSD curses. SVr4 curses is better

    known today as X/Open Curses

    '
  dev_url: https://ncurses.scripts.mit.edu/?p=ncurses.git
  doc_url: https://invisible-island.net/ncurses/NCURSES-Programming-HOWTO.html
  home: https://invisible-island.net/ncurses/
  license: MIT AND X11
  license_family: MIT
  license_file: COPYING
  summary: Library for text-based user interfaces
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 47c27664-29d8-451c-a155-b6cfee04d17a
  recipe-maintainers:
    - jakirkham
    - jjhelmus
  remote_url: git@github.com:AnacondaRecipes/ncurses-feedstock.git
  sha: 3be0b0a1221bd1a02b7ecd72b2d59fd77c7d1437
  skip-lints:
    - build_tools_must_be_in_build
    - host_section_needs_exact_pinnings
