# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/ktietz/Code/oss/aggregate/qt-webengine-feedstock/recipe, last modified Sun Jul 24 18:11:42 2022
# ------------------------------------------------

package:
  name: qt-webengine
  version: 5.15.9
source:
  - folder: qtwebengine
    patches:
      - patches/webengine/qt_webengine-3.15.9.patch
    url: https://anduin.linuxfromscratch.org/BLFS/qtwebengine/qtwebengine-5.15.9.tar.xz
  - folder: qtwebengine-chromium
    git_rev: 87-based
    git_url: https://code.qt.io/cgit/qt/qtwebengine-chromium.git
    patches:
      - patches/webengine/qt_3rdparty.patch
      - patches/webengine/qtweb_chromium.patch
build:
  detect_binary_files_with_prefix: true
  missing_dso_whitelist:
    - /System/Library/Frameworks/CoreLocation.framework/**
    - /usr/lib/libbsm.0.dylib
    - /usr/lib/libcups.2.dylib
    - /usr/lib/libresolv.9.dylib
    - /usr/lib/libsandbox.1.dylib
  number: '4'
  run_exports:
    - qt-webengine >=5.15.9,<5.16.0a0
  string: h2903aaf_4
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2022.07.19 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - curl 7.82.0 h1a28f6b_0
    - expat 2.4.4 hc377ac9_0
    - gawk 5.1.0 ha11acfe_0
    - gettext 0.21.0 h826f4ad_0
    - git 2.34.1 pl5340h646bd76_0
    - icu 68.1 hc377ac9_0
    - krb5 1.19.2 h3b8d789_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.82.0 hc6d1d07_0
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210910 h1a28f6b_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hc377ac9_4
    - libiconv 1.16 h1a28f6b_2
    - libllvm12 12.0.0 h12f7ac0_4
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libtool 2.4.6 hc377ac9_1008
    - libuv 1.39.0 h1a28f6b_0
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - lz4-c 1.9.3 hc377ac9_0
    - make 4.3 h620ffc9_1
    - ncurses 6.3 h1a28f6b_3
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - nodejs 16.13.1 h2b10c05_0
    - openssl 1.1.1q h1a28f6b_0
    - patch 2.7.6 h1a28f6b_1001
    - pcre2 10.37 h37e8eca_1
    - perl 5.34.0 h1230e6a_0
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.10.4 hbdb9e5c_0
    - readline 8.1.2 h1a28f6b_1
    - rhash 1.4.1 hf27765b_1
    - sed 4.8 h1a28f6b_0
    - sqlite 3.38.5 h1058600_0
    - tapi 1100.0.11 ha21211d_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022a hda174b7_0
    - xz 5.2.5 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
    - zstd 1.5.2 h8574219_0
  host:
    - ca-certificates 2022.07.19 hca03da5_0
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang-tools 12.0.0 default_he099f3d_4
    - clangdev 12.0.0 default_he099f3d_4
    - clangxx 12.0.0 default_he099f3d_4
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h98b2900_1
    - gst-plugins-base 1.14.1 hf0a386a_0
    - gstreamer 1.14.1 he09cfb7_0
    - icu 68.1 hc377ac9_0
    - jpeg 9e h1a28f6b_0
    - krb5 1.19.2 h3b8d789_0
    - libclang 12.0.0 default_hc321e17_4
    - libclang-cpp 12.0.0 default_he099f3d_4
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210910 h1a28f6b_0
    - libffi 3.4.2 hc377ac9_4
    - libiconv 1.16 h1a28f6b_2
    - libllvm12 12.0.0 h12f7ac0_4
    - libpng 1.6.37 hb8d0fd4_0
    - libpq 12.9 h65cfe13_3
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - llvmdev 12.0.0 h12f7ac0_4
    - lz4-c 1.9.3 hc377ac9_0
    - ncurses 6.3 h1a28f6b_3
    - nspr 4.33 hc377ac9_0
    - nss 3.74 h142855e_0
    - openssl 1.1.1q h1a28f6b_0
    - pcre 8.45 hc377ac9_0
    - qt-main 5.15.2 ha2d02b5_4
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.38.5 h1058600_0
    - xz 5.2.5 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
    - zstd 1.5.2 h8574219_0
  run:
    - libcxx >=12.0.0
    - qt-main >=5.15,<6.0a0
    - qt-main >=5.15.2,<5.16.0a0
  run_constrained:
    - qt 5.15.9
test:
  files:
    - test/webengine/main-qtwebengine.cpp
    - test/webengine/main.qml
    - test/webengine/qml.qrc
    - test/webengine/qrc_qml.cpp
    - test/webengine/qtwebengine.pro
  requires:
    - clangxx_osx-arm64 12.*
    - make
  script: run_webengine_test.sh
about:
  description: 'Qt helps you create connected devices, UIs & applications that run

    anywhere on any device, on any operating system at any time.

    '
  dev_url: https://github.com/qt
  doc_url: http://doc.qt.io/
  home: http://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: Qt is a cross-platform application and UI framework.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Tobias-Fischer
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
