# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/clone-z7vpbma9/recipe, last modified Mon Feb  7 02:21:02 2022
# ------------------------------------------------

package:
  name: nss
  version: '3.74'
source:
  fn: nss-3.74.tgz
  patches:
    - 0002-Use-AR-in-makefiles.patch
    - nss-3.55-standalone-1.patch
    - remove_hw_accel_osxarm64.patch
  sha256: 88928811f9f40f87d42e2eaccdf6e454562e51486067f2ddbe90aa47ea6cd056
  url: https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_74_RTM/src/nss-3.74.tar.gz
build:
  ignore_run_exports:
    - zlib
  number: '0'
  run_exports:
    - nss >=3.74,<4.0a0
  string: h142855e_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2021.10.26 hca03da5_2
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - expat 2.4.1 hc377ac9_2
    - krb5 1.19.2 h3b8d789_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.80.0 hc6d1d07_0
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210910 h1a28f6b_0
    - libev 4.33 h1a28f6b_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.9.0 hf27765b_1
    - libuv 1.39.0 h1a28f6b_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - lz4-c 1.9.3 hc377ac9_0
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1m h1a28f6b_0
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1230e6a_0
    - pkg-config 0.29.2 h1a28f6b_0
    - rhash 1.4.1 hf27765b_1
    - tapi 1100.0.11 ha21211d_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
    - zstd 1.5.0 h8574219_0
  host:
    - libcxx 12.0.0 hf6beb65_1
    - ncurses 6.3 h1a28f6b_2
    - nspr 4.33 hc377ac9_0
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.37.0 h1058600_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - libcxx >=12.0.0
    - nspr >=4.33,<5
    - nspr >=4.33,<5.0a0
    - sqlite >=3.37.0,<4.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsoftokn3${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsoftokn3.chk
    - test -f ${PREFIX}/lib/libnss3${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsmime3${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libssl3${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libnssckbi${SHLIB_EXT}
about:
  description: 'Network Security Services (NSS) is a set of libraries designed to
    support

    cross-platform development of security-enabled client and server

    applications. Applications built with NSS can support SSL v3, TLS,

    PKCS #5, PKCS #7, PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates,

    and other security standards.

    '
  dev_url: https://hg.mozilla.org/projects/nss
  doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
  home: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
  license: MPL-2.0
  license_family: OTHER
  license_file: nss/COPYING
  summary: A set of libraries designed to support cross-platform development of security-enabled
    client and server applications.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - marcelotrevisani
