# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_1bqaqd_iyk/clone/recipe, last modified Thu Mar 30 09:55:13 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.3.1
source:
  patches:
    - patches/01-deprecations-version-fallback.patch
  sha256: f0203ae42a8a360170e8aebd45e42b6c8bf283d44b9016ef4b30451c0b55c8dc
  url: https://github.com/conda/conda/archive/23.3.1.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  string: py39hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.19.0 h80987f9_0
    - ca-certificates 2023.01.10 hca03da5_0
    - curl 7.88.1 h80987f9_0
    - expat 2.4.9 hc377ac9_0
    - gdbm 1.18 h8fe7016_4
    - gettext 0.21.0 h13f89a0_1
    - git 2.34.1 pl5340h646bd76_0
    - icu 68.1 hc377ac9_0
    - krb5 1.19.4 h8380606_0
    - libcurl 7.88.1 h0f1d93c_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libiconv 1.16 h1a28f6b_2
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libxml2 2.10.3 h372ba2a_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - pcre2 10.37 h37e8eca_1
    - perl 5.34.0 h1a28f6b_2
    - readline 8.2 h1a28f6b_0
    - tk 8.6.12 hb8d0fd4_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - boltons 23.0.0 py39hca03da5_0
    - ca-certificates 2023.01.10 hca03da5_0
    - certifi 2022.12.7 py39hca03da5_0
    - cffi 1.15.1 py39h80987f9_3
    - conda-package-handling 2.0.2 py39hca03da5_0
    - conda-package-streaming 0.7.0 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - packaging 23.0 py39hca03da5_0
    - pip 23.0.1 py39hca03da5_0
    - pluggy 1.0.0 py39hca03da5_1
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.9.16 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - ruamel.yaml 0.17.21 py39h1a28f6b_0
    - ruamel.yaml.clib 0.2.6 py39h1a28f6b_1
    - setuptools 65.6.3 py39hca03da5_0
    - sqlite 3.41.1 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - toolz 0.12.0 py39hca03da5_0
    - tqdm 4.65.0 py39h86d0a89_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py39hca03da5_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstandard 0.19.0 py39h80987f9_0
  run:
    - boltons >=23.0.0
    - conda-package-handling >=1.3.0
    - jsonpatch >=1.32
    - packaging
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.9,<3.10.0a0
    - requests >=2.20.1,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=31.0.1
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3.18.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  downstreams:
    - conda-smithy
  imports:
    - conda
    - conda_env
  requires: null
about:
  description: 'Conda is an open source package management system and environment
    management system for installing multiple versions of software packages and their
    dependencies and switching easily between them. It works on Linux, OS X and Windows,
    and was created for Python programs but can package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1bfd5ba3-0f31-486d-beb6-acd15187900f
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - jezdez
    - jjhelmus
    - kalefranz
    - kenodegard
    - mbargull
    - mcg1969
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - travishathaway
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: 5f3030eb353df2781bbe2e1abee86e8eaf90eaef
