# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_69c3tq4a3k/clone/recipe, last modified Fri Jan 20 13:26:02 2023
# ------------------------------------------------

package:
  name: krb5
  version: 1.19.4
source:
  sha256: bb44dfd7ab4fd80c5ba4c7a751ad4669f6e0bd2d418fe6bf94fbc0d0af278a02
  url: https://github.com/krb5/krb5/archive/krb5-1.19.4-final.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - tk
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '0'
  run_exports:
    - krb5 >=1.19.4,<1.20.0a0
  string: h8380606_0
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - bison 3.7.5 hc377ac9_1
    - ca-certificates 2022.10.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - flex 2.6.4 hc4ed4cf_1
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.8.16 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.1 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - libedit 3.1.20221030 h80987f9_0
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - tk 8.6.12 hb8d0fd4_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - libedit >=3.1.20221030,<3.2.0a0
    - libedit >=3.1.20221030,<4.0a0
    - openssl >=1.1.1s,<1.1.2a
test:
  requires:
    - python 3.8.*
about:
  description: 'Kerberos is a network authentication protocol. It is designed to provide
    strong authentication for client/server applications by using secret-key cryptography.

    '
  dev_url: https://kerberos.org/dist/index.html
  doc_url: https://web.mit.edu/kerberos/krb5-1.19/doc/index.html
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 694f9bbb-b5f5-449a-9111-4f2235d5f7a4
  recipe-maintainers:
    - chenghlee
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/krb5-feedstock.git
  sha: 1d5c6f16873f4c66f09fd95fc85c99adbddf26f1
