# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_3bxrxn10s2/clone/recipe, last modified Tue Feb 21 06:39:45 2023
# ------------------------------------------------

package:
  name: giflib
  version: 5.2.1
source:
  - patches:
      - CVE-2022-28506.patch
    sha256: 31da5562f44c5f15d63340a09a4fd62b48c45620cd302f77a6d9acf0077879bd
    url: https://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
build:
  number: '3'
  run_exports:
    - giflib >=5.2.1,<5.3.0a0
  string: h80987f9_3
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.4.9 hc377ac9_0
    - krb5 1.19.4 h8380606_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcurl 7.87.0 h0f1d93c_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libuv 1.39.0 h1a28f6b_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - lz4-c 1.9.4 h313beb8_0
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - patch 2.7.6 h1a28f6b_1001
    - rhash 1.4.1 hf27765b_1
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.2 h8574219_0
  run: []
test:
  commands:
    - gifbuild -h
    - giffix -h
    - giftext -h
    - gifclrmp -h
    - gif2rgb -h
about:
  description: 'The GIFLIB project maintains the giflib service library, which has
    been pulling images

    out of GIFs since 1989. It is deployed everywhere you can think of and some places
    you

    probably can''t - graphics applications and web browsers on multiple operating
    systems,

    game consoles, smartphones, and likely your ATM too.

    '
  dev_url: https://giflib.sourceforge.net
  doc_url: https://giflib.sourceforge.net
  home: https://giflib.sourceforge.net
  license: MIT
  license_family: MIT
  license_file:
    - COPYING
  summary: Library for reading and writing gif images
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 3b3ca3a8-9086-48a9-8e4c-c3198ede1571
  recipe-maintainers:
    - 183amir
    - isuruf
    - katietz
    - msarahan
    - ocefpaf
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/giflib-feedstock.git
  sha: 8995916c66c79706414622acd41ebb83892e6068
