# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libclang
  version: 12.0.0
source:
  - folder: .
    patches:
      - patches/0001-Find-conda-gcc-installation.patch
      - patches/0002-Fix-sysroot-detection-for-linux.patch
      - patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
      - patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch
      - patches/0005-Set-VERSION-in-osx-as-well.patch
      - patches/0006-Fix-crosscompiling-LLVM-tools.patch
    sha256: e26e452e91d4542da3ebbf404f024d3e1cbf103f4cd110c26bf0a19621cca9ed
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang-12.0.0.src.tar.xz
  - folder: tools/extra
    patches:
      - patches/0001-Make-clangd-CompletionModel-not-depend-on-directory-.patch
    sha256: ad41e0b527a65ade95c1ba690a5434cefaab4a2daa1be307caaa1e8541fe6d5c
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang-tools-extra-12.0.0.src.tar.xz
build:
  number: 4
  string: default_hc321e17_4
  track_features: null
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.4.13 hca03da5_1
    - clang_bootstrap_osx-arm64 12.0.0 ha993bc6_2
    - cmake 3.20.4 h94ae478_0
    - expat 2.3.0 hc4ed4cf_2
    - krb5 1.19.1 h8e9bd5e_0
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_0
    - libedit 3.1.20210216 h1230e6a_1
    - libssh2 1.9.0 h7405173_1
    - libuv 1.39.0 h1230e6a_0
    - lz4-c 1.9.3 hc4ed4cf_0
    - make 4.3 h620ffc9_1
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - rhash 1.4.1 h7405173_1
    - xz 5.2.4 h1230e6a_0
    - zlib 1.2.11 hca03da5_3
    - zstd 1.4.9 hd783eca_0
  host:
    - clang 12.0.0 hca03da5_4
    - libcxx 12.0.0 hf6beb65_0
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm 12.0.0 hc8b9a67_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - llvmdev 12.0.0 h12f7ac0_4
    - zlib 1.2.11 hca03da5_3
  run:
    - libcxx >=12.0.0
    - libllvm12 >=12.0.0,<12.1.0a0
test:
  commands:
    - test -f "$PREFIX/lib/libclang.dylib"
    - test -f "$PREFIX/lib/libclang.12.dylib"
about:
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: Development headers and libraries for Clang
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - chrisburr
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
    - xhochy
