# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/Code/oss/aggregate/gettext-feedstock/recipe, last modified Thu May 13 11:05:15 2021
# ------------------------------------------------

package:
  name: gettext
  version: 0.21.0
source:
  - patches:
      - 0000-Add-ax_with_curses.m4-and-try-to-use-it.patch
    sha256: d20fcbb537e02dcf1383197ba05bd0734ef7bf5db06bdb241eb69b7d16b73192
    url: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.xz
build:
  env:
    - SKIP_GNULIB=--skip-gnulib
  ignore_run_exports:
    - ncurses
  number: '0'
  run_exports:
    - gettext >=0.21.0,<1.0a0
  string: h826f4ad_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - autoconf-archive 2021.02.19 hd3eb1b0_0
    - automake 1.16.2 pl5340hca03da5_1
    - ca-certificates 2021.4.13 hca03da5_1
    - cctools_osx-arm64 949.0.1 h722190c_22
    - clang 12.0.0 hca03da5_3
    - clang-12 12.0.0 default_h7e67d58_3
    - clang_osx-arm64 12.0.0 hcb56dc5_2
    - clangxx 12.0.0 default_h7e67d58_3
    - clangxx_osx-arm64 12.0.0 h39b79ac_2
    - compiler-rt 12.0.0 h9f55edf_2
    - compiler-rt_osx-arm64 12.0.0 h362012c_2
    - ld64_osx-arm64 530 h05de83e_22
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_h7e67d58_3
    - libcxx 12.0.0 hf6beb65_0
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h63e4c0e_3
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h63e4c0e_3
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - openssl 1.1.1j h1230e6a_0
    - perl 5.34.0 h1230e6a_0
    - pkg-config 0.29.2 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - wget 1.20.1 h7623bd3_0
    - zlib 1.2.11 hca03da5_3
  host:
    - icu 68.1 hc4ed4cf_0
    - libcxx 12.0.0 hf6beb65_0
    - libiconv 1.16 h1230e6a_0
    - libxml2 2.9.10 h3d7e406_3
    - llvm-openmp 12.0.0 haf9daa7_1
    - ncurses 6.2 hc4ed4cf_0
    - xz 5.2.4 h1230e6a_0
    - zlib 1.2.11 hca03da5_3
  run:
    - libcxx >=12.0.0
    - libiconv >=1.16,<2.0a0
    - libxml2 >=2.9.10,<2.10.0a0
    - llvm-openmp >=12.0.0
test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextpo$SHLIB_EXT
    - test -f ${PREFIX}/lib/libgettextsrc$SHLIB_EXT
    - test -f ${PREFIX}/lib/libintl$SHLIB_EXT
about:
  home: https://www.gnu.org/software/gettext/
  license: GPL-2.0
  license_file: COPYING
  summary: Internationalization package
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - scopatz
