# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: gst-plugins-base
  version: 1.14.1
source:
  - sha256: 28d82b0d261544a9bf85b429399929e4986eb00efcf1ce16cc71d269a4c3186c
    url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.1.tar.xz
  - folder: plugins_base
    sha256: 1026c7c3082d825d9b5d034c1a6dd8a4ebab60eb3738b0a0afde4ad2dc0b0db5
    url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.14.1.tar.xz
build:
  activate_in_script: true
  number: 1
  run_exports:
    - gst-plugins-base >=1.14.1,<1.15.0a0
  string: h313beb8_1
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h514c7bf_2
    - gobject-introspection 1.72.0 py310hddb4ab5_1
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - meson 0.64.1 py310hca03da5_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1t h1a28f6b_0
    - pcre 8.45 hc377ac9_0
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.10.9 hc0d8a6c_0
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.1 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h98b2900_1
    - gstreamer >=1.14.1,<2.0a0
    - icu 68.1 hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libxml2 2.9.12 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - pcre 8.45 hc377ac9_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.11 h5a0b063_4
  run:
    - glib >=2.69.1,<3.0a0
    - gstreamer >=1.14.1,<2.0a0
    - libcxx >=14.0.6
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libgstallocators-1.0.dylib
    - test -f $PREFIX/lib/libgstapp-1.0.dylib
    - test -f $PREFIX/lib/libgstaudio-1.0.dylib
    - test -f $PREFIX/lib/libgstfft-1.0.dylib
    - test -f $PREFIX/lib/libgstpbutils-1.0.dylib
    - test -f $PREFIX/lib/libgstriff-1.0.dylib
    - test -f $PREFIX/lib/libgstrtp-1.0.dylib
    - test -f $PREFIX/lib/libgstrtsp-1.0.dylib
    - test -f $PREFIX/lib/libgstsdp-1.0.dylib
    - test -f $PREFIX/lib/libgsttag-1.0.dylib
    - test -f $PREFIX/lib/libgstvideo-1.0.dylib
about:
  description: 'GStreamer Base Plug-ins is a well-groomed and well-maintained collection
    of

    GStreamer plug-ins and elements, spanning the range of possible types of

    elements one would want to write for GStreamer.

    '
  doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs
  summary: GStreamer Base Plug-ins
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6cf17d70-ef56-4ee4-81f9-f64fda8109f4
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
  remote_url: git@github.com:AnacondaRecipes/gstreamer-feedstock.git
  sha: cac772cb4456e3eb7e2e918d9f899c58338dfee0
