# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/libvpx-feedstock/recipe, last modified Sat Aug 14 08:44:29 2021
# ------------------------------------------------

package:
  name: libvpx
  version: 1.10.0
source:
  sha256: 85803ccbdbdd7a3b03d930187cb055f1353596969c1f92ebec2db839fa4f834a
  url: https://github.com/webmproject/libvpx/archive/v1.10.0.tar.gz
build:
  number: '0'
  run_exports:
    - libvpx >=1.10.0,<1.11.0a0
  string: hc377ac9_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.4.13 hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - curl 7.71.1 h6b60437_1
    - expat 2.4.1 hc377ac9_2
    - gettext 0.21.0 h826f4ad_0
    - git 2.32.0 pl5340h646bd76_1
    - icu 68.1 hc4ed4cf_0
    - krb5 1.19.1 h8e9bd5e_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210216 h1230e6a_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libssh2 1.9.0 h7405173_1
    - libtool 2.4.6 h1230e6a_0
    - libxml2 2.9.10 h3d7e406_3
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pcre2 10.37 h4e217f5_0
    - perl 5.34.0 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - tk 8.6.10 h6b60437_0
    - xz 5.2.5 h1a28f6b_0
    - yasm 1.3.0 h1a28f6b_2
    - zlib 1.2.11 hca03da5_3
  host:
    - libcxx 12.0.0 hf6beb65_1
  run:
    - libcxx >=12.0.0
test:
  commands:
    - test -f ${PREFIX}/lib/libvpx.a
    - test -f ${PREFIX}/lib/libvpx.dylib
    - conda inspect linkages -p $PREFIX libvpx
    - conda inspect objects -p $PREFIX libvpx
about:
  description: 'libvpx is a free software video codec library from

    Google and the Alliance for Open Media (AOMedia).

    It serves as the reference software implementation for

    the video coding formats VP8 and VP9, and for AV1 a

    special fork named libaom that was stripped of

    backwards compatibility.

    '
  dev_url: https://chromium.googlesource.com/webm/libvpx
  doc_url: http://www.webmproject.org/vp9/
  home: https://www.webmproject.org/
  license: 3-clause BSD
  license_family: BSD
  summary: A high-quality, open video format for the web
extra:
  copy_test_source_files: true
  final: true
