# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ab19r4bji3/clone/recipe, last modified Wed Dec  7 08:26:39 2022
# ------------------------------------------------

package:
  name: cffi
  version: 1.15.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
    - apple-jit.patch
    - setup-linux.patch
  sha256: d400bfb9a37b1351253cb402671cea7e89bdecc294e8016a707f6d1d8ac934f9
  url: https://pypi.io/packages/source/c/cffi/cffi-1.15.1.tar.gz
build:
  missing_dso_whitelist: null
  number: '3'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ab19r4bji3/croot/cffi_1670423206034/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  string: py39h80987f9_3
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pip 22.2.2 py39hca03da5_0
    - python 3.9.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.5.0 py39hca03da5_0
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - libffi >=3.4,<3.5
    - pycparser
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://foss.heptapod.net/pypy/cffi
  doc_source_url: https://foss.heptapod.net/pypy/cffi/-/tree/branch/default/doc/source
  doc_url: https://cffi.readthedocs.io/en/latest/
  home: https://cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ab8c9bb3-896d-476c-a13a-7147c1e15b7c
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cffi-feedstock.git
  sha: 1d0b98bd6262574564cad512fac5e0fe6e1df9ad
