# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_92c84b_bge/clone/recipe, last modified Fri Nov 25 02:19:11 2022
# ------------------------------------------------

package:
  name: glib
  version: 2.69.1
source:
  patches:
    - patches/0001-replace-hardcoded-paths.patch
    - patches/0003-add-install_rpath-to-meson-build-files.patch
  sha256: f92f34057a091fc8638d91f10cece842cb8618e9a1090b0ddb19cc15a21bf39c
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.69/glib-2.69.1.tar.xz
build:
  ignore_run_exports: null
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '2'
  run_exports:
    - glib >=2.69.1,<3.0a0
  string: h514c7bf_2
requirements:
  build:
    - ca-certificates 2022.10.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - certifi 2022.9.24 py38hca03da5_0
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - meson 0.62.2 py38hca03da5_0
    - ncurses 6.3 h1a28f6b_3
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1s h1a28f6b_0
    - patch 2.7.6 h1a28f6b_1001
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.8.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.5.0 py38hca03da5_0
    - sqlite 3.40.0 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - gettext 0.21.0 h826f4ad_0
    - icu 68.1 hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pcre 8.45 hc377ac9_0
    - python 3.8.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - gettext >=0.21.0,<1.0a0
    - libcxx >=14.0.6
    - libffi >=3.4,<3.5
    - libffi >=3.4,<4.0a0
    - libiconv >=1.16,<2.0a0
    - pcre >=8.45,<9.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.dylib
    - test ! -f ${PREFIX}/lib/libgobject-2.0.la
    - gdbus help
    - gio version
    - gio-querymodules .
    - glib-compile-resources --help
    - glib-compile-schemas --help
    - gobject-query --help
    - gresource help
    - gtester --help
about:
  description: 'GLib provides the core application building blocks for libraries and

    applications written in C. It provides the core object system used in

    GNOME, the main loop implementation, and a large set of utility functions

    functions for strings and common data structures.

    '
  dev_url: https://git.gnome.org/browse/glib/
  doc_source_url: https://git.gnome.org/browse/glib/tree/docs
  doc_url: https://developer.gnome.org/glib/unstable/
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 92b724aa-fc40-4bbc-b74e-9202b866b836
  recipe-maintainers:
    - ccordoba12
    - chenghlee
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/glib-feedstock.git
  sha: a86988ace330cd95191acf3ee4ca67b918b03467
