# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e946luvhc3/clone/recipe, last modified Thu Mar 16 06:15:15 2023
# ------------------------------------------------

package:
  name: packaging
  version: '23.0'
source:
  sha256: b6ad297f8907de0fa2fe1ccbd26fdaf387f5f47c7275fedf8cce89f99446cf97
  url: https://pypi.io/packages/source/p/packaging/packaging-23.0.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e946luvhc3/croot/packaging_1678965323926/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps -vv
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2023.01.10 hca03da5_0
    - certifi 2022.12.7 py39hca03da5_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - pip 23.0.1 py39hca03da5_0
    - python 3.9.16 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.6.3 py39hca03da5_0
    - sqlite 3.41.1 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py39hca03da5_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  dev_url: https://github.com/pypa/packaging
  doc_source_url: https://github.com/pypa/packaging/tree/main/docs
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e9216b1c-2ff0-4690-aab9-ccb115489978
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/packaging-feedstock.git
  sha: a525d3ca60583c6131c37d030c19e8fc9b0b11a9
