# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/icu-feedstock/recipe, last modified Thu Sep  2 17:43:55 2021
# ------------------------------------------------

package:
  name: icu
  version: '68.1'
source:
  - patches:
      - mach-port-t.patch
    sha256: a9f2e3d8b4434b8e53878b4308bd1e6ee51c9c7042e2b1a376abefb6fbb29f2d
    url: https://github.com/unicode-org/icu/releases/download/release-68-1/icu4c-68_1-src.tgz
  - folder: source/data
    sha256: 03ea8b4694155620548c8c0ba20444f1e7db246cc79e3b9c4fc7a960b160d510
    url: https://github.com/unicode-org/icu/releases/download/release-68-1/icu4c-68_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=68.1,<69.0a0
  string: hc377ac9_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.2.1 h1a28f6b_1
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - libcxx 12.0.0 hf6beb65_1
  run:
    - libcxx >=12.0.0
test:
  commands:
    - test -f $PREFIX/lib/libicudata.a
    - test -f $PREFIX/lib/libicudata.68.1.dylib
    - test -f $PREFIX/lib/libicui18n.a
    - test -f $PREFIX/lib/libicui18n.68.1.dylib
    - test -f $PREFIX/lib/libicuio.a
    - test -f $PREFIX/lib/libicuio.68.1.dylib
    - test -f $PREFIX/lib/libicutest.a
    - test -f $PREFIX/lib/libicutest.68.1.dylib
    - test -f $PREFIX/lib/libicutu.a
    - test -f $PREFIX/lib/libicutu.68.1.dylib
    - test -f $PREFIX/lib/libicuuc.a
    - test -f $PREFIX/lib/libicuuc.68.1.dylib
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

    Unicode and Globalization support for software applications. ICU is

    widely portable and gives applications the same results on all platforms

    and between C/C++ and Java software.

    '
  dev_url: http://source.icu-project.org/repos/icu/
  doc_url: http://site.icu-project.org/design
  home: http://site.icu-project.org/
  license: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
