# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/clone-3zutzgb0/recipe, last modified Mon Jan 31 02:21:31 2022
# ------------------------------------------------

package:
  name: nspr
  version: '4.33'
source:
  sha256: b23ee315be0e50c2fb1aa374d17f2d2d9146a835b1a79c1918ea15d075a693d7
  url: https://ftp.mozilla.org/pub/nspr/releases/v4.33/src/nspr-4.33.tar.gz
build:
  number: '0'
  run_exports:
    - nspr >=4.33,<5.0a0
  string: hc377ac9_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - gettext 0.21.0 h826f4ad_0
    - gnuconfig 2021.05.24 hd3eb1b0_0
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libxml2 2.9.12 h8c5e841_0
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - perl 5.34.0 h1230e6a_0
    - sed 4.8 h1a28f6b_0
    - tapi 1100.0.11 ha21211d_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  host:
    - libcxx 12.0.0 hf6beb65_1
  run:
    - libcxx >=12.0.0
test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}
    - test -d ${PREFIX}/include/nspr
    - test -f ${PREFIX}/bin/nspr-config
about:
  description: 'NetScape Portable Runtime (NSPR) provides platform independence for

    non-GUI operating system facilities. These facilities include threads,

    thread synchronization, normal file and network I/O, interval timing and

    calendar time, basic memory management (malloc and free) and shared

    library linking.

    '
  dev_url: https://hg.mozilla.org/projects/nspr
  doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions
  home: https://hg.mozilla.org/projects/nspr
  license: MPL-2.0
  license_family: OTHER
  license_file: nspr/LICENSE
  summary: A platform-neutral API for system level and libc-like functions.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - marcelotrevisani
