# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_19t7k81exs/clone/recipe, last modified Wed Apr 19 16:25:14 2023
# ------------------------------------------------

package:
  name: typing_extensions
  version: 4.5.0
source:
  sha256: 5cb5f4a79139d699607b3ef622a1dedafa84e115ab0024e0d9c044a9479ca7cb
  url: https://pypi.io/packages/source/t/typing_extensions/typing_extensions-4.5.0.tar.gz
build:
  number: '0'
  script: python -m pip install --no-deps --ignore-installed .
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2023.01.10 hca03da5_0
    - flit-core 3.8.0 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - pip 23.0.1 py39hca03da5_0
    - python 3.9.16 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 66.0.0 py39hca03da5_0
    - sqlite 3.41.2 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.38.4 py39hca03da5_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.9,<3.10.0a0
about:
  description: 'The typing module was added to the standard library in Python 3.5,
    but

    many new features have been added to the module since then.

    This means users of older Python versions who are unable to upgrade will not be

    able to take advantage of new types added to the typing module, such as

    typing.Protocol or typing.TypedDict.


    The typing_extensions module contains backports of these changes.

    Experimental types that will eventually be added to the ``typing``

    module are also included in typing_extensions.

    '
  dev_url: https://github.com/python/typing_extensions
  doc_url: https://github.com/python/typing_extensions/blob/main/README.md
  home: https://github.com/python/typing_extensions
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backported and Experimental Type Hints for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 19458d1c-8e66-4144-850f-a6e8a9223fe7
  recipe-maintainers:
    - djsutherland
  remote_url: git@github.com:AnacondaRecipes/typing_extensions-feedstock.git
  sha: e579f828909231b65616e1ef5f78d01c28ab1b54
