# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e9xhel3kyj/clone/recipe, last modified Wed Oct 26 12:31:51 2022
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.4
source:
  sha256: 79ffa99156810e58876dd6374af0b7bff88f9a4580ca8b8468c414c5c2454bb8
  url: https://github.com/conda/pycosat/archive/0.6.4.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e9xhel3kyj/croot/pycosat_1666805516297/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: py39h1a28f6b_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2022.07.19 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - certifi 2022.9.24 py310hca03da5_0
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hc377ac9_4
    - libllvm12 12.0.0 h12f7ac0_4
    - libllvm14 14.0.6 h4b41812_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1q h1a28f6b_0
    - pip 22.2.2 py310hca03da5_0
    - python 3.10.6 hbdb9e5c_1
    - readline 8.2 h1a28f6b_0
    - setuptools 63.4.1 py310hca03da5_0
    - sqlite 3.39.3 h1058600_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022e h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2022.07.19 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hc377ac9_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1q h1a28f6b_0
    - pip 22.2.2 py39hca03da5_0
    - python 3.9.13 hbdb9e5c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 63.4.1 py39hca03da5_0
    - sqlite 3.39.3 h1058600_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022e h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.4"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.org/project/pycosat/
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  license_url: https://github.com/conda/pycosat/blob/0.6.4/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e98f8c70-1211-4038-94c5-a0f46147dfdf
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pycosat-feedstock.git
  sha: 18eedcf1f31f03a7e1ac629331f92a182cb57adb
