# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libllvm12
  version: 12.0.0
source:
  patches:
    - patches/D101972.patch
    - patches/llvm-config-no-libLLVM.diff
    - patches/numba-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    - patches/osx_ver.patch
    - patches/pass-through-qemu-ld-prefix.diff
  sha256: 49dc47c8697a1a0abd4ee51629a696d7bfe803662f2a7252a3b16fc75f3a8b50
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/llvm-12.0.0.src.tar.xz
build:
  activate_in_script: true
  number: 4
  run_exports:
    - libllvm12 >=12.0.0,<12.1.0a0
  string: h12f7ac0_4
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.4.13 hca03da5_1
    - certifi 2020.12.5 py39hca03da5_0
    - clang_bootstrap_osx-arm64 12.0.0 ha993bc6_2
    - cmake 3.20.4 h94ae478_0
    - expat 2.3.0 hc4ed4cf_2
    - krb5 1.19.1 h8e9bd5e_0
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_0
    - libedit 3.1.20210216 h1230e6a_1
    - libffi 3.3 hc4ed4cf_2
    - libiconv 1.16 h1230e6a_0
    - libssh2 1.9.0 h7405173_1
    - libuv 1.39.0 h1230e6a_0
    - lz4-c 1.9.3 hc4ed4cf_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pip 21.0.1 py39hca03da5_0
    - python 3.9.6 hc8d96b9_3
    - readline 8.1 h1230e6a_0
    - rhash 1.4.1 h7405173_1
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.35.4 h9835d80_0
    - tk 8.6.10 h6b60437_0
    - tzdata 2021a h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.4 h1230e6a_0
    - zlib 1.2.11 hca03da5_3
    - zstd 1.4.9 hd783eca_0
  host:
    - libcxx 12.0.0 hf6beb65_0
    - zlib 1.2.11 hca03da5_3
  run:
    - libcxx >=12.a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libLLVM-12${SHLIB_EXT}
about:
  dev_url: https://github.com/llvm-mirror/llvm
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - isuruf
    - jakirkham
    - mingwandroid
    - timsnyder
