# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_b7yrbsawof/clone/recipe, last modified Mon Nov 14 09:36:51 2022
# ------------------------------------------------

package:
  name: mypy
  version: '0.981'
source:
  sha256: ad77c13037d3402fbeffda07d51e3f228ba078d1c7096a73759c9419ea031bf4
  url: https://pypi.io/packages/source/m/mypy/mypy-0.981.tar.gz
build:
  entry_points:
    - dmypy = mypy.dmypy.client:console_entry
    - mypy = mypy.__main__:console_entry
    - stubgen = mypy.stubgen:main
    - stubtest = mypy.stubtest:main
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_b7yrbsawof/croot/mypy_1668440220235/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hc377ac9_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pip 22.2.2 py39hca03da5_0
    - python 3.9.13 hbdb9e5c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.5.0 py39hca03da5_0
    - sqlite 3.39.3 h1058600_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022f h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - mypy_extensions >=0.4.3,<2
    - psutil >=4.0
    - python >=3.9,<3.10.0a0
    - toml
    - tomli >=1.1.0
    - typing_extensions >=3.10
test:
  commands:
    - pip check
    - mypy --help
    - stubgen --help
    - dmypy --help
    - stubtest --help
  imports:
    - mypy
    - mypy.dmypy
    - mypy.plugins
    - mypy.server
  requires:
    - pip
about:
  description: 'Add type annotations to your Python programs, and use mypy to type
    check

    them. Mypy is essentially a Python linter on steroids, and it can catch

    many programming errors by analyzing your program, withoutactually having

    to run it.  Mypy has a powerful type system with features such as type

    inference, gradual typing, generics and union types.

    '
  dev_url: https://github.com/python/mypy
  doc_url: https://mypy.readthedocs.io
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optional static typing for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b79e036c-762a-408d-afd8-54a22ec783f6
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/mypy-feedstock.git
  sha: c39b096998ab5121bb4d7c3cbd50e4141d3f0c01
