# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_25zq_880tz/clone/recipe, last modified Tue Mar 14 08:25:48 2023
# ------------------------------------------------

package:
  name: harfbuzz
  version: 4.3.0
source:
  sha256: 32184860ddc0b264ff95010e1c64e596bd746fe4c2e34014a1185340cdddeba6
  url: https://github.com/harfbuzz/harfbuzz/archive/4.3.0.tar.gz
build:
  number: '1'
  run_exports:
    - harfbuzz >=4.3.0,<5.0a0
  string: he9eebac_1
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h514c7bf_2
    - gobject-introspection 1.72.0 py310hddb4ab5_2
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - meson 0.64.1 py310hca03da5_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1t h1a28f6b_0
    - pcre 8.45 hc377ac9_0
    - pkg-config 0.29.2 h1a28f6b_0
    - pthread-stubs 0.3 h1a28f6b_1
    - python 3.10.9 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.1 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.01.10 hca03da5_0
    - cairo 1.16.0 h302bd0f_4
    - expat 2.4.9 hc377ac9_0
    - fontconfig 2.14.1 h6b8db82_1
    - freetype 2.10.4 h1192e45_0
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h514c7bf_2
    - gobject-introspection 1.72.0 py310hddb4ab5_2
    - graphite2 1.3.14 hc377ac9_1
    - icu 68.1 hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libpng 1.6.39 h80987f9_0
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - pcre 8.45 hc377ac9_0
    - pixman 0.40.0 h1a28f6b_0
    - pkg-config 0.29.2 h1a28f6b_0
    - python 3.10.9 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.1 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  run:
    - cairo >=1.16.0,<2.0a0
    - freetype >=2.10.4,<3.0a0
    - glib >=2.69.1,<3.0a0
    - graphite2 >=1.3.14,<2.0a0
    - icu >=68.1,<69.0a0
    - libcxx >=14.0.6
test:
  commands:
    - test -f $PREFIX/lib/libharfbuzz-icu.dylib
    - test -f $PREFIX/lib/libharfbuzz.dylib
    - test -f $PREFIX/include/harfbuzz/hb-ft.h
    - test -f $PREFIX/share/gir-1.0/HarfBuzz-0.0.gir
about:
  description: "HarfBuzz is a text shaping library. Using the HarfBuzz library allows\n\
    programs to convert a sequence of Unicode input into properly formatted\nand positioned\
    \ glyph output\u2014for any writing system and language.\n"
  dev_url: https://github.com/harfbuzz/harfbuzz
  doc_url: https://harfbuzz.github.io/
  home: https://harfbuzz.github.io/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A text shaping library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 251e9b2b-24c9-41e9-9320-2a65dac9657c
  recipe-maintainers:
    - ocefpaf
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/harfbuzz-feedstock.git
  sha: 578e05263e020ef71915d9b42b2de827cf45ec2b
