# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/toml-0.10.2-on-linux_64, last modified Fri Mar 19 15:06:06 2021
# ------------------------------------------------

package:
  name: toml
  version: 0.10.2
source:
  fn: toml-0.10.2.tar.gz
  sha256: b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f
  url: https://pypi.io/packages/source/t/toml/toml-0.10.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/toml_1616166611790/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_1
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.2 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.35.1 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=2.7
test:
  commands:
    - conda inspect linkages -p $PREFIX toml
  imports:
    - toml
about:
  home: https://github.com/uiri/toml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python lib for TOML.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - holgern
    - rlaverde
