# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libpq
  version: '12.9'
source:
  patches:
    - 0001-fix-win-zlib-name.patch
    - 0002-disable-new-dtags.patch
    - 0003-update-location-of-krb5-files.patch
  sha256: 89fda2de33ed04a98548e43f3ee5f15b882be17505d631fe0dd1a540a2b56dce
  url: https://ftp.postgresql.org/pub/source/v12.9/postgresql-12.9.tar.bz2
build:
  ignore_run_exports: null
  number: 3
  run_exports:
    - libpq >=12.9,<13.0a0
  string: h65cfe13_3
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.12 h5a0b063_2
  host:
    - ca-certificates 2022.4.26 hca03da5_0
    - krb5 1.19.2 h3b8d789_0
    - libedit 3.1.20210910 h1a28f6b_0
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1o h1a28f6b_0
    - readline 8.1.2 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
  run:
    - krb5 >=1.19.2,<1.20.0a0
    - openssl >=1.1.1o,<1.1.2a
    - readline >=8.1.2,<9.0a0
    - zlib >=1.2.12,<1.3.0a0
test:
  commands:
    - pg_config
    - test -f $PREFIX/lib/libpq.5.12.dylib
    - test -f $PREFIX/lib/libpq.5.dylib
    - test -f $PREFIX/lib/libpq.dylib
about:
  summary: The postgres runtime libraries and utilities (not the server itself)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 33f633be-33d0-4edb-b33a-e75cc5aef75b
  recipe-maintainers:
    - gillins
    - mariusvniekerk
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/postgresql-feedstock.git
  sha: 6f5a88ad0121177404ae985bda1035b1c85fde55
