# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/Code/oss/cf-packages/bzip2-feedstock/recipe, last modified Sun Jun 20 20:52:29 2021
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  patches:
    - 0001-cross.patch
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
  url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
build:
  number: '4'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: h620ffc9_4
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h722190c_22
    - clang 12.0.0 hca03da5_3
    - clang-12 12.0.0 default_h7e67d58_3
    - clang_osx-arm64 12.0.0 hcb56dc5_2
    - clangxx 12.0.0 default_h7e67d58_3
    - compiler-rt 12.0.0 h9f55edf_2
    - compiler-rt_osx-arm64 12.0.0 h362012c_2
    - ld64_osx-arm64 530 h05de83e_22
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_h7e67d58_3
    - libcxx 12.0.0 hf6beb65_0
    - libllvm12 12.0.0 h63e4c0e_3
    - llvm-tools 12.0.0 h63e4c0e_3
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  run: []
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.dylib
about:
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  doc_url: http://www.bzip.org/docs.html
  home: http://www.bzip.org/
  license: bzip2-1.0.6
  license_family: BSD
  license_file: LICENSE
  summary: high-quality data compressor
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jlanga
    - mingwandroid
    - msarahan
    - pelson
