# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_11146a2b-93c2-444c-a378-ad4fac363e991s0r1hnp/clone/recipe, last modified Mon Jul 18 01:39:38 2022
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.1.3
source:
  fn: conda-content-trust-0.1.3.tar.gz
  sha256: 50a2732dcf3612bdff2b36171e3ebc72a74bbc258543a5aa2618218406b30a0d
  url: https://github.com/conda/conda-content-trust/archive/0.1.3.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_11146a2b-93c2-444c-a378-ad4fac363e991s0r1hnp/croots/recipe/conda-content-trust_1658126383571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install --no-deps --ignore-installed -vv .
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.4.26 hca03da5_0
    - certifi 2022.6.15 py39hca03da5_0
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1q h1a28f6b_0
    - pip 22.1.2 py39hca03da5_0
    - python 3.9.12 hbdb9e5c_1
    - readline 8.1.2 h1a28f6b_1
    - setuptools 61.2.0 py39hca03da5_0
    - sqlite 3.38.5 h1058600_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
  run:
    - cryptography
    - python >=3.9,<3.10.0a0
    - six
test:
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help
  imports:
    - conda_content_trust
  requires:
    - pip
    - pytest
    - pytest-cov
    - ruamel_yaml
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.rst
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 11146a2b-93c2-444c-a378-ad4fac363e99
  remote_url: git@github.com:AnacondaRecipes/conda-content-trust-feedstock.git
  sha: 4e69a87949a2597071655306e4ed8c062ddd8518
