# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_4bvqsmkp73/clone/recipe, last modified Wed Oct 26 10:30:36 2022
# ------------------------------------------------

package:
  name: freetype
  version: 2.12.1
source:
  sha256: efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.12.1.tar.gz
build:
  number: '0'
  run_exports:
    - freetype >=2.12.1,<3.0a0
  string: h1192e45_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hc377ac9_4
    - libllvm12 12.0.0 h12f7ac0_4
    - libllvm14 14.0.6 h4b41812_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - libpng 1.6.37 hb8d0fd4_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - libpng >=1.6.37,<1.7.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: https://gitlab.freedesktop.org/freetype/freetype
  doc_source_url: https://gitlab.freedesktop.org/freetype/freetype
  doc_url: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/README
  home: https://freetype.org/
  license: GPL-2-only and LicenseRef-FreeType
  license_family: Other
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  license_url: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/LICENSE.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4b921b83-7273-45b6-bd74-d5f29d1c2a0e
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/freetype-feedstock.git
  sha: 7112aa3b6f409b1bde037cbc16f274ecfecfd533
