# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_82kat2k1rl/clone/recipe, last modified Tue Mar 14 03:39:00 2023
# ------------------------------------------------

package:
  name: cairo
  version: 1.16.0
source:
  patches:
    - 0001-Ref-and-destroy-the-cairo-surface-handed-off-to-Core.patch
  sha256: 5e7b29b3f113ef870d1e3ecf8adf21f923396401604bda16d44be45e66052331
  url: https://cairographics.org/releases/cairo-1.16.0.tar.xz
build:
  number: '4'
  run_exports:
    - cairo >=1.16.0,<2.0a0
  string: h302bd0f_4
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - automake 1.16.5 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 h7ec7a93_1
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - expat 2.4.9 hc377ac9_0
    - fontconfig 2.14.1 h6b8db82_1
    - freetype 2.10.4 h1192e45_0
    - gettext 0.21.0 h826f4ad_0
    - glib 2.69.1 h514c7bf_2
    - icu 68.1 hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libpng 1.6.39 h80987f9_0
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - pcre 8.45 hc377ac9_0
    - pixman 0.40.0 h1a28f6b_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  run:
    - fontconfig >=2.14.1,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - glib >=2.69.1,<3.0a0
    - icu >=68.1,<69.0a0
    - libpng >=1.6.39,<1.7.0a0
    - pixman >=0.40.0,<1.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - cairo-trace --help
    - test -f $PREFIX/lib/libcairo.a
    - test -f $PREFIX/lib/libcairo.dylib
    - test -f $PREFIX/lib/libcairo-gobject.a
    - test -f $PREFIX/lib/libcairo-gobject.dylib
    - test -f $PREFIX/lib/libcairo-script-interpreter.a
    - test -f $PREFIX/lib/libcairo-script-interpreter.dylib
    - test -f $PREFIX/lib/pkgconfig/cairo-quartz.pc
    - test -f $PREFIX/include/cairo/cairo.h
    - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h
about:
  description: 'Cairo is a 2D graphics library with support for multiple output devices.

    It is designed to produce consistent output on all output media while

    taking advantage of display hardware acceleration when available.

    '
  dev_url: https://gitlab.freedesktop.org/cairo/cairo
  doc_url: https://cairographics.org/documentation/
  home: https://cairographics.org/
  license: LGPL-2.1-or-later or MPL-1.1
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING-LGPL-2.1
    - COPYING-MPL-1.1
  summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 82612610-6d34-42d5-8b14-ce5ddc896c3f
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/cairo-feedstock.git
  sha: 63d32c5a38a21e28927f196b5d06416267531933
