# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/pixman-feedstock/recipe, last modified Sat Aug 14 09:36:00 2021
# ------------------------------------------------

package:
  name: pixman
  version: 0.40.0
source:
  patches: null
  sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc
  url: http://cairographics.org/releases/pixman-0.40.0.tar.gz
build:
  number: '0'
  run_exports:
    - pixman >=0.40.0,<1.0a0
  string: h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  run: []
test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1.a
about:
  description: 'Pixman is a low-level software library for pixel manipulation, providing

    features such as image compositing and trapezoid rasterization.

    '
  dev_url: https://cgit.freedesktop.org/pixman/
  home: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: A low-level software library for pixel manipulation.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
