# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_8c_qoky_1b/clone/recipe, last modified Mon Jan  9 15:12:32 2023
# ------------------------------------------------

package:
  name: cryptography
  version: 38.0.4
source:
  sha256: 175c1a818b87c9ac80bb7377f5520b7f31b3ef2a0004e2420319beadedb67290
  url: https://pypi.io/packages/source/c/cryptography/cryptography-38.0.4.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_8c_qoky_1b/croot/cryptography_1673298759921/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: py39h834c97f_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm12 12.0.0 h12f7ac0_4
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - rust 1.64.0 h80987f9_0
    - rust_osx-arm64 1.46.0 hc4ed4cf_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.12.7 py39hca03da5_0
    - cffi 1.15.1 py39h80987f9_3
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pip 22.3.1 py39hca03da5_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.9.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 65.5.0 py39hca03da5_0
    - setuptools-rust 1.5.2 py39hca03da5_0
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - typing_extensions 4.4.0 py39hca03da5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - cffi >=1.12
    - openssl
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - pytest -n auto -k "not (test_der_x509_certificate_extensions[x509/PKITS_data/certs/ValidcRLIssuerTest28EE.crt]
      or test_x509_csr_extensions or test_no_leak_free or test_no_leak_no_malloc or
      test_leak or test_load_pkcs12_key_and_certificates[pkcs12/cert-key-aes256cbc.p12]
      or test_create_certificate_with_extensions or test_ec_derive_private_key or
      test_ec_private_numbers_private_key or test_create_ocsp_request or test_write_pkcs12_key_and_certificates
      or test_errors or test_load_pkcs12_key_and_certificates[pkcs12/cert-aes256cbc-no-key.p12]
      or test_ec_private_numbers_private_key or test_pem_x509_certificate_extensions[x509/cryptography.io.pem]
      or test_create_crl_with_idp or test_no_leak_gc or test_x25519_pubkey_from_private_key)"
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 38.0.4.*
    - hypothesis >=1.11.4,!=3.79.2
    - iso8601
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-subtests
    - pytest-xdist
    - pytz
  source_files:
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/38.0.4/docs/index.rst
  doc_url: https://cryptography.io/en/38.0.4/
  home: https://github.com/pyca/cryptography
  license: (BSD-3-Clause OR Apache-2.0) AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/pyca/cryptography/blob/38.0.4/vectors/LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8c9e7352-ea38-459b-b5b7-b8a126f4462e
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 2ea8f1f3704a07beda7ed68cfdbfba63c14fde7d
