# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d0e5ffbf-5cf1-45be-8693-c5dff8108a2awhthtjlq/clone/recipe, last modified Thu Jul  7 01:31:43 2022
# ------------------------------------------------

package:
  name: tomli
  version: 2.0.1
source:
  sha256: de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f
  url: https://pypi.io/packages/source/t/tomli/tomli-2.0.1.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d0e5ffbf-5cf1-45be-8693-c5dff8108a2awhthtjlq/croots/recipe/tomli_1657175508477/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.4.26 hca03da5_0
    - certifi 2022.6.15 py39hca03da5_0
    - flit-core 3.3.0 pyhd3eb1b0_0
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_4
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1p h1a28f6b_0
    - pip 21.2.4 py39hca03da5_0
    - python 3.9.12 hbdb9e5c_1
    - readline 8.1.2 h1a28f6b_1
    - setuptools 61.2.0 py39hca03da5_0
    - sqlite 3.38.5 h1058600_0
    - tk 8.6.12 hb8d0fd4_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  files:
    - example.toml
  imports:
    - tomli
  requires:
    - pip
about:
  dev_url: https://github.com/hukkin/tomli
  doc_url: https://github.com/hukkin/tomli/blob/master/README.md
  home: https://github.com/hukkin/tomli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple TOML parser
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d0e5ffbf-5cf1-45be-8693-c5dff8108a2a
  recipe-maintainers:
    - thewchan
  remote_url: git@github.com:AnacondaRecipes/tomli-feedstock.git
  sha: 2bfefbb1d7cc33690713e989b8054a9de751e281
