# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/ffmpeg-feedstock/recipe, last modified Fri Aug 13 16:02:12 2021
# ------------------------------------------------

package:
  name: ffmpeg
  version: 4.2.2
source:
  - sha256: 83f9a9aa0acf8036daf47494d99a8c31154a18ebb6841d89878ba47783559bd0
    url: https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.gz
build:
  missing_dso_whitelist:
    - /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
  number: '0'
  run_exports:
    - ffmpeg >=4.2.2,<4.3.0a0
  string: h04105a8_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.4.13 hca03da5_1
    - freetype 2.10.4 h1192e45_0
    - gettext 0.21.0 h826f4ad_0
    - gmp 6.2.1 hc377ac9_0
    - gnutls 3.6.15 h887c41c_0
    - icu 68.1 hc4ed4cf_0
    - lame 3.100 h1a28f6b_0
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libidn2 2.3.1 h1a28f6b_0
    - libopus 1.3 h1a28f6b_1
    - libpng 1.6.37 hb8d0fd4_0
    - libtasn1 4.16.0 h1a28f6b_0
    - libunistring 0.9.10 h1a28f6b_0
    - libvpx 1.10.0 hc377ac9_0
    - libxml2 2.9.10 h3d7e406_3
    - llvm-openmp 12.0.0 haf9daa7_1
    - nettle 3.7.3 h84b5d62_1
    - openh264 1.8.0 h98b2900_0
    - openssl 1.1.1j h1230e6a_0
    - x264 1!152.20180806 h1a28f6b_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - bzip2 >=1.0.8,<2.0a0
    - freetype >=2.10.4,<3.0a0
    - gmp >=6.2.1,<7.0a0
    - gnutls >=3.6.15,<3.7.0a0
    - lame >=3.100,<3.101.0a0
    - libcxx >=12.0.0
    - libiconv >=1.16,<2.0a0
    - libopus >=1.3,<2.0a0
    - libvpx >=1.10.0,<1.11.0a0
    - openh264 >=1.8.0,<1.9.0a0
    - openssl >=1.1.1j,<1.1.2a
    - x264 >=1!152.20180806,<1!153
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -codecs
    - ffmpeg -loglevel panic -protocols | grep "https"
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"
    - test -f $PREFIX/lib/libavcodec.dylib
    - test -f $PREFIX/lib/libavdevice.dylib
    - test -f $PREFIX/lib/libswresample.dylib
    - test -f $PREFIX/lib/libpostproc.dylib
    - test -f $PREFIX/lib/libavfilter.dylib
    - test -f $PREFIX/lib/libswresample.dylib
    - test -f $PREFIX/lib/libavcodec.dylib
    - test -f $PREFIX/lib/libavformat.dylib
    - test -f $PREFIX/lib/libswscale.dylib
    - test -f $PREFIX/lib/libavresample.dylib
about:
  dev_url: https://ffmpeg.org/developer.html
  doc_url: https://ffmpeg.org/documentation.html
  home: http://www.ffmpeg.org/
  license: GPL 3
  license_file: COPYING.GPLv3
  summary: Cross-platform solution to record, convert and stream audio and video.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - 183amir
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal
