# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: c-ares
  version: 1.19.0
source:
  sha256: bfceba37e23fd531293829002cac0401ef49a6dc55923f7f92236585b7ad1dd3
  url: https://c-ares.org/download/c-ares-1.19.0.tar.gz
build:
  number: 0
  run_exports:
    - c-ares >=1.19.0,<2.0a0
  string: h80987f9_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - cmake-no-system 3.16.5 hc377ac9_2
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1t h1a28f6b_0
    - python 3.11.0 hc0d8a6c_3
    - readline 8.2 h1a28f6b_0
    - sqlite 3.40.1 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
  run: []
  run_constraint:
    - c-ares-static <0a0
test:
  commands:
    - test -f ${PREFIX}/include/ares.h
    - test -f ${PREFIX}/lib/libcares${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcares.a
    - test ! -f ${PREFIX}/lib/libcares_static.a
about:
  description: 'c-ares is a C library for asynchronous DNS requests (including name
    resolves).

    '
  dev_url: https://github.com/c-ares/c-ares
  doc_url: https://c-ares.org/docs.html
  home: https://c-ares.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1ec4babb-58e3-415a-afd6-8542a5655aa3
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/c-ares-feedstock.git
  sha: 424f3ae1929dc99db54027f0e0809344242e0a90
