# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e05937d9-13ea-4bbf-906c-4bdce3fb672dzu26h6gx/clone/recipe, last modified Tue Apr 26 09:18:04 2022
# ------------------------------------------------

package:
  name: libiconv
  version: '1.16'
source:
  - patches: null
    sha256: e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
    url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
build:
  number: '2'
  run_exports:
    - libiconv >=1.16,<2.0a0
  string: h1a28f6b_2
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 hc377ac9_1008
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.12 h5a0b063_2
  host: []
  run: []
test:
  commands:
    - iconv --help
about:
  description: 'This library provides an iconv() implementation, for use on systems
    which don''t have one,

    or whose implementation cannot convert from/to Unicode.

    '
  dev_url: https://git.savannah.gnu.org/cgit/libiconv.git/tree/
  doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.16/iconv.1.html
  home: https://www.gnu.org/software/libiconv/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Provides iconv for systems which don't have one (or that cannot convert
    from/to Unicode.)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e05937d9-13ea-4bbf-906c-4bdce3fb672d
  recipe-maintainers:
    - jakirkham
    - jhamman
    - mingwandroid
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/libiconv-feedstock.git
  sha: 43365045d6ecbb87a49e6c228ba8bd0868c43094
