# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_6027i_d23u/clone/recipe, last modified Fri Dec  9 08:50:08 2022
# ------------------------------------------------

package:
  name: pip
  version: 22.3.1
source:
  sha256: 65fd48317359f3af8e593943e6ae1506b66325085ea64b706a998c6e83eeaf38
  url: https://pypi.io/packages/source/p/pip/pip-22.3.1.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  number: '0'
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - python 3.9.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.5.0 py39hca03da5_0
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.9,<3.10.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
about:
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io/en/stable/
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 600268c9-60c4-4114-b580-af949f1b164c
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pip-feedstock.git
  sha: 35deb01080818ce878c3d1b2bcc423f65e1ebc08
