# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: libcurl
  version: 7.88.1
source:
  sha256: 8224b45cce12abde039c12dc0711b7ea85b104b9ad534d6e4c5b4e188a61c907
  url: https://curl.se/download/curl-7.88.1.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=7.88.1,<8.0a0
  string: h0f1d93c_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2023.01.10 hca03da5_0
    - krb5 1.19.4 h8380606_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - ncurses 6.4 h313beb8_0
    - openssl 1.1.1t h1a28f6b_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - krb5 >=1.19.4,<1.20.0a0
    - libnghttp2 >=1.46.0
    - libnghttp2 >=1.46.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.10.0,<2.0a0
    - openssl >=1.1.1t,<1.1.2a
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9dcd0c2d-d472-4704-a8aa-abc23a042996
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: c67f4d661d99cfcf7d50303534b72de4df329a33
