# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_21wrdckisg/clone/recipe, last modified Mon Oct 24 02:03:07 2022
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.13
source:
  patches:
    - cmake-pkg-config.patch
  sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
  url: http://zlib.net/zlib-1.2.13.tar.gz
build:
  number: '0'
  run_exports:
    - zlib >=1.2.13,<1.3.0a0
  string: h5a0b063_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 12.0.0 ha993bc6_3
    - cmake-no-system 3.16.5 hc377ac9_2
    - libcxx 14.0.6 h848a8c0_0
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
  host:
    - ripgrep 13.0.0 hb333ee5_0
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/zlib.h
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz.dylib
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: Other
  license_file: zlib.h
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 213027e2-500d-4a42-9806-5e43e2b7ac4e
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/zlib-feedstock.git
  sha: 188c70c233f0a26b10b46629324a0f9caf125209
