# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/openh264-feedstock/recipe, last modified Sat Aug 14 09:17:24 2021
# ------------------------------------------------

package:
  name: openh264
  version: 1.8.0
source:
  fn: openh264-v1.8.0.tar.gz
  sha256: 08670017fd0bb36594f14197f60bebea27b895511251c7c64df6cd33fc667d34
  url: https://github.com/cisco/openh264/archive/v1.8.0.tar.gz
build:
  number: '0'
  run_exports:
    - openh264 >=1.8.0,<1.9.0a0
  string: h98b2900_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - libcxx 12.0.0 hf6beb65_1
    - zlib 1.2.11 hca03da5_3
  run:
    - libcxx >=12.0.0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - h264enc -h
    - test -f $PREFIX/bin/h264dec
    - test -f $PREFIX/lib/libopenh264.dylib
    - conda inspect linkages -p $PREFIX openh264
    - conda inspect objects -p $PREFIX openh264
about:
  dev_url: https://github.com/cisco/openh264
  doc_url: https://github.com/cisco/openh264
  home: http://www.openh264.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenH264 is a codec library which supports H.264 encoding and decoding
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - 183amir
    - sdvillal
