# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_clone-a83_l0hb/recipe, last modified Fri Mar  4 04:49:05 2022
# ------------------------------------------------

package:
  name: eigen
  version: 3.3.7
source:
  fn: eigen-3.3.7.tar.gz
  sha1: 3e8ab94ff389ae4b3103f5dda77c826d85b9c1d5
  url: https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz
build:
  number: '1'
  string: h525c30c_1
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2022.2.1 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - expat 2.4.4 hc377ac9_0
    - krb5 1.19.2 h3b8d789_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.80.0 hc6d1d07_0
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210910 h1a28f6b_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hc377ac9_2
    - libllvm12 12.0.0 h12f7ac0_4
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.9.0 hf27765b_1
    - libuv 1.39.0 h1a28f6b_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - lz4-c 1.9.3 hc377ac9_0
    - ncurses 6.3 h1a28f6b_2
    - ninja 1.10.2 py310h525c30c_3
    - openssl 1.1.1m h1a28f6b_0
    - python 3.10.0 hbdb9e5c_5
    - readline 8.1.2 h1a28f6b_1
    - rhash 1.4.1 hf27765b_1
    - sqlite 3.37.2 h1058600_0
    - tapi 1100.0.11 ha21211d_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
    - zstd 1.5.0 h8574219_0
  host:
    - libcxx 12.0.0 hf6beb65_1
  run:
    - libcxx >=12.0.0
test:
  commands:
    - test -d $PREFIX/include/eigen3
  files:
    - test.cc
  requires:
    - clangxx_osx-arm64 12.*
about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  license_family: Other
  summary: C++ template library for linear algebra
extra:
  copy_test_source_files: true
  final: true
