# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: numpy-base
  version: 1.23.5
source:
  patches:
    - patches/0001-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
  sha256: 1b1766d6f397c18153d40015ddfc79ddb715cabadc04d2d228d4e5a8bc4ded1a
  url: https://github.com/numpy/numpy/releases/download/v1.23.5/numpy-1.23.5.tar.gz
build:
  entry_points:
    - f2py = numpy.f2py.f2py2e:main
  number: 0
  string: py39h90707a3_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - llvm-tools 14.0.6 h7ec7a93_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - blas 1.0 openblas
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.12.7 py39hca03da5_0
    - cython 0.29.32 py39hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libgfortran 5.0.0 11_3_0_hca03da5_28
    - libgfortran5 11.3.0 h009349e_28
    - libopenblas 0.3.20 hea475bc_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.3 h1a28f6b_3
    - nomkl 3.0 0
    - openblas-devel 0.3.20 hca03da5_0
    - openssl 1.1.1s h1a28f6b_0
    - packaging 22.0 py39hca03da5_0
    - pip 22.3.1 py39hca03da5_0
    - python 3.9.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 58.0.4 py39hca03da5_1
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - blas * openblas
    - libcxx >=14.0.6
    - libopenblas >=0.3.20,<1.0a0
    - python >=3.9,<3.10.0a0
test:
  commands:
    - test -e $SP_DIR/numpy/distutils/site.cfg
about:
  description: 'NumPy is the fundamental package needed for scientific computing with
    Python.

    '
  dev_url: https://github.com/numpy/numpy
  doc_source_url: https://github.com/numpy/numpy/tree/main/doc
  doc_url: https://numpy.org/doc/stable/reference/
  home: https://numpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/numpy/numpy/blob/main/LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d1bd64ad-2e32-49a3-a89f-9570741277f4
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
  remote_url: git@github.com:AnacondaRecipes/numpy-feedstock.git
  sha: 3d70a5ca694fb618e981339c3d06f1e9686f1c3d
