# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_58gpsa_6af/clone/recipe, last modified Thu Dec  8 08:02:17 2022
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.7.0
source:
  sha256: 87be2b1c365a0e04d15579b9137b139f0837c52198bdba21c5ac071fc13efd75
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.7.0.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_58gpsa_6af/croot/conda-package-streaming_1670508144037/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install --no-build-isolation . -vv
  string: py39hca03da5_0
requirements:
  host:
    - ca-certificates 2022.10.11 hca03da5_0
    - certifi 2022.9.24 py39hca03da5_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pip 22.2.2 py39hca03da5_0
    - python 3.9.15 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - setuptools 65.5.0 py39hca03da5_0
    - sqlite 3.40.0 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.9,<3.10.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 58a8cc6b-c932-4e0a-bc4e-e61f7bea8e12
  recipe-maintainers:
    - dholth
  remote_url: git@github.com:AnacondaRecipes/conda-package-streaming-feedstock.git
  sha: 0d6428f0165f2fa2fd2de24ce50216dc442be5d8
