# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/tmpt55kago8/recipe, last modified Fri Oct 29 11:03:10 2021
# ------------------------------------------------

package:
  name: lerc
  version: '3.0'
source:
  sha256: 8c0148f5c22d823eff7b2c999b0781f8095e49a7d3195f13c68c5541dd5740a1
  url: https://github.com/Esri/lerc/archive/v3.0.tar.gz
build:
  number: '0'
  run_exports:
    - lerc >=3.0,<4.0a0
  string: hc377ac9_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2021.10.26 hca03da5_2
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - cmake 3.19.6 hae769c0_1
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - expat 2.4.1 hc377ac9_2
    - krb5 1.19.2 h3b8d789_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210216 h1a28f6b_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libssh2 1.9.0 hf27765b_1
    - libuv 1.39.0 h1a28f6b_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - lz4-c 1.9.3 hc377ac9_0
    - make 4.3 h620ffc9_1
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - rhash 1.4.1 hf27765b_1
    - tapi 1100.0.11 ha21211d_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
    - zstd 1.4.9 h8574219_1
  host:
    - libcxx 12.0.0 hf6beb65_1
  run:
    - libcxx >=12.0.0
test:
  commands:
    - test -f ${PREFIX}/lib/libLerc${SHLIB_EXT}
    - test -f ${PREFIX}/include/Lerc_types.h
about:
  description: 'LERC is an open-source image or raster format which

    supports rapid encoding and decoding for any pixel type

    (not just RGB or Byte). Users set the maximum compression

    error per pixel while encoding, so the precision of the

    original input image is preserved (within user defined

    error bounds).

    '
  home: https://github.com/Esri/lerc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LERC - Limited Error Raster Compression
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
