# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/tmp3j_evh85/recipe, last modified Wed Dec 22 04:58:41 2021
# ------------------------------------------------

package:
  name: mypy_extensions
  version: 0.4.3
source:
  fn: mypy_extensions-0.4.3.tar.gz
  sha256: 2d82818f5bb3e369420cb3c4060a7970edba416647068eb4c5343488a6c604a8
  url: https://pypi.io/packages/source/m/mypy_extensions/mypy_extensions-0.4.3.tar.gz
build:
  number: '1'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py39hca03da5_1
requirements:
  host:
    - ca-certificates 2021.10.26 hca03da5_2
    - certifi 2021.5.30 py39hca03da5_1
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.4 py39hca03da5_0
    - python 3.9.7 hc70090a_1
    - readline 8.1 h1a28f6b_0
    - setuptools 58.0.4 py39hca03da5_1
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - mypy_extensions
  requires:
    - pip
about:
  description: 'The ''mypy_extensions'' module defines experimental extensions to
    the

    standard ''typing'' module that are supported by the mypy typechecker.

    '
  dev_url: https://github.com/python/mypy/blob/master/extensions
  doc_url: https://mypy.readthedocs.io
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Experimental type system extensions for programs checked with the mypy
    typechecker.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nehaljwani
    - skupr-anaconda
