# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_f0x4iml_tn/clone/recipe, last modified Wed Dec 14 01:04:01 2022
# ------------------------------------------------

package:
  name: fontconfig
  version: 2.14.1
source:
  sha256: ae480e9ca34382790312ff062c625ec70df94d6d9a9366e2b2b3d525f7f90387
  url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.14.1.tar.gz
build:
  binary_has_prefix_files:
    - lib/libfontconfig.*.dylib*
  number: '1'
  run_exports:
    - fontconfig >=2.14.1,<3.0a0
  string: h6b8db82_1
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - automake 1.16.5 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.4.9 hc377ac9_0
    - gdbm 1.18 h8fe7016_4
    - gettext 0.21.0 h826f4ad_0
    - gperf 3.1 hc377ac9_0
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - libxml2 2.9.14 h8c5e841_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.3 h1a28f6b_3
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  host:
    - coreutils 8.32 h1a28f6b_0
    - expat 2.4.9 hc377ac9_0
    - freetype 2.10.4 h1192e45_0
    - icu 68.1 hc377ac9_0
    - libcxx 14.0.6 h848a8c0_0
    - libiconv 1.16 h1a28f6b_2
    - libpng 1.6.37 hb8d0fd4_0
    - libxml2 2.9.14 h8c5e841_0
    - unzip 6.0 h1a28f6b_0
    - xz 5.2.8 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - expat >=2.4.9,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - libxml2 >=2.9.14,<2.10.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  requires:
    - pkg-config
about:
  description: 'Fontconfig is a library designed to provide system-wide font configuration,

    customization and application access.

    '
  dev_url: https://gitlab.freedesktop.org/fontconfig/fontconfig
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  home: https://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A library for configuring and customizing font access.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f0df9dcc-9946-4068-88f5-fa86dece6d0f
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - katietz
    - mingwandroid
    - ocefpaf
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/fontconfig-feedstock.git
  sha: 1453105a4c7343aaf587872d721815a0934da544
