# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_c9872xen4u/clone/recipe, last modified Wed Feb 22 03:24:37 2023
# ------------------------------------------------

package:
  name: libwebp-base
  version: 1.2.4
source:
  sha256: 7bf5a8a28cc69bcfa8cb214f2c3095703c6b73ac5fba4d5480c205331d9494df
  url: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.4.tar.gz
build:
  number: '1'
  run_exports:
    - libwebp-base
  string: h80987f9_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 h7ec7a93_1
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  run: []
  run_constrained:
    - libwebp 1.2.4
test:
  commands:
    - test -f $PREFIX/lib/libwebp.dylib
    - test ! -f $PREFIX/lib/libwebp.a
    - test $PREFIX/pkgconfig/libwebp.pc
    - test -f $PREFIX/lib/libwebpdemux.dylib
    - test ! -f $PREFIX/lib/libwebpdemux.a
    - test $PREFIX/pkgconfig/libwebpdemux.pc
    - test -f $PREFIX/lib/libwebpmux.dylib
    - test ! -f $PREFIX/lib/libwebpmux.a
    - test $PREFIX/pkgconfig/libwebpmux.pc
    - test -f $PREFIX/lib/libwebpdecoder.dylib
    - test ! -f $PREFIX/lib/libwebpdecoder.a
    - test $PREFIX/pkgconfig/libwebpdecoder.pc
    - test -f $PREFIX/include/webp/decode.h || (echo "decode.h not found" && exit
      1)
    - test -f $PREFIX/include/webp/demux.h || (echo "demux.h not found" && exit 1)
    - test -f $PREFIX/include/webp/encode.h || (echo "encode.h not found" && exit
      1)
    - test -f $PREFIX/include/webp/mux_types.h || (echo "mux_types.h not found" &&
      exit 1)
    - test -f $PREFIX/include/webp/mux.h || (echo "mux.h not found" && exit 1)
    - test -f $PREFIX/include/webp/types.h || (echo "types.h not found" && exit 1)
    - test ! -f $PREFIX/bin/cwebp
    - test ! -f $PREFIX/bin/dwebp
    - test ! -f $PREFIX/bin/gif2webp
    - test ! -f $PREFIX/bin/img2webp
    - test ! -f $PREFIX/bin/webpinfo
    - test ! -f $PREFIX/bin/webpmux
about:
  description: 'WebP is a method of lossy and lossless compression that can be used
    on a

    large variety of photographic, translucent and graphical images found on the

    web. The degree of lossy compression is adjustable so a user can choose the

    trade-off between file size and image quality.

    libwebp-base provides the headers and shared libraries. For cwebp and dwep,

    binaries install libwebp.

    '
  dev_url: https://chromium.googlesource.com/webm/libwebp
  doc_url: https://developers.google.com/speed/webp/docs/using
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: WebP image library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: c966d42b-d76e-4d90-b37d-90b05c480e57
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libwebp-base-feedstock.git
  sha: a7de8454178e6430f8ed4430ff048d96789360c1
